name: Publish Library
on:
  pull_request:
    branches: [master]
    types: [closed]
  push:
jobs:
  publish-library:
    permissions:
      id-token: write
      contents: read
    uses: ngmd-repo/ngmd-pipelines/.github/workflows/npm-deploy.yml@feature/pipelines
    with:
      title: ${{ github.event.pull_request.title }}
      publish-directory: "./lib"
      run-build: false
      run-ci: false
    secrets:
      NPM_LIBRARY_TOKEN: ${{ secrets.NPM_LIBRARY_TOKEN }}
